### ISSUE TITLE
节点启动quagga时异常

### ISSUE THREAD

**Issue by wenkaiqiu** [wenkaiqiu/miniNExT#5]
正确运行时的结果：
![true.png](https://images.zenhubusercontent.com/57ac2a36e40e5714b16d3ad3/69fbbdf5-d569-4b5a-ad3a-cbed342d8c9c)
异常时的结果：
![false.png](https://images.zenhubusercontent.com/57ac2a36e40e5714b16d3ad3/3ade11ee-330f-4614-a0c2-a7d8d65e750b)

**Comment by wenkaiqiu** [comment]
ovs运行报错：
`ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)`

**Comment by wenkaiqiu** [comment]
exit时异常
```
a1 Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "start.py", line 61, in stopNetwork
    net.stop()
  File "/home/mininet/NetworkSimulator/miniNExT/mininext/net.py", line 57, in stop
    Mininet.stop(self)
  File "/home/mininet/NetworkSimulator/mininet/mininet/net.py", line 595, in stop
    host.terminate()
  File "/home/mininet/NetworkSimulator/mininet/mininet/node.py", line 268, in terminate
    os.killpg( self.shell.pid, signal.SIGHUP )
ProcessLookupError: [Errno 3] No such process
```

**Comment by wenkaiqiu** [comment]
疑似挂载配置文件时异常，需排查

**Comment by wenkaiqiu** [comment]
> 疑似挂载配置文件时异常，需排查

修改思路，按照net.buildFromTopo步骤逐步排查：controller -> hosts -> switches -> links

**Comment by wenkaiqiu** [comment]
验证结果：hosts启动过程异常，并在服务启动之前。
addHost过程中调用的构造函数或startShell方法异常可能性较大。

**Comment by wenkaiqiu** [comment]
> exit时异常
> 
> ```
> a1 Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "start.py", line 61, in stopNetwork
>     net.stop()
>   File "/home/mininet/NetworkSimulator/miniNExT/mininext/net.py", line 57, in stop
>     Mininet.stop(self)
>   File "/home/mininet/NetworkSimulator/mininet/mininet/net.py", line 595, in stop
>     host.terminate()
>   File "/home/mininet/NetworkSimulator/mininet/mininet/node.py", line 268, in terminate
>     os.killpg( self.shell.pid, signal.SIGHUP )
> ProcessLookupError: [Errno 3] No such process
> ```

**原因**：对比新旧代码发现新代码使用了`os.killpg( self.shell.pid, signal.SIGHUP )`杀死进程，而旧代码使用`os.kill( self.pid, signal.SIGKILL )`杀死进程。经测试发现MiniNExT使用了PID Namespace，导致self.pid与self.shell.pid不一致，同时导致了group pid不一致，真实gpid应为`self.pid`。
**解决方法**：在MiniNExT中覆盖node.terminate方法，并使用`os.killpg( self.pid, signal.SIGHUP )`杀死进程

**Comment by wenkaiqiu** [comment]
> 验证结果：hosts启动过程异常，并在服务启动之前。
> addHost过程中调用的构造函数或startShell方法异常可能性较大。

调试发现出错发生在mount过程中，进一步定位

**Comment by wenkaiqiu** [comment]
mininet2.1.0不提供mount Namespace功能，故MiniNExT单独实现，而mininet2.3.0实现了该功能，推测是两者的实现发生了冲突。

尝试融合，首先需要阅读代码找到异同点。

**Comment by wenkaiqiu** [comment]
> mininet2.1.0不提供mount Namespace功能，故MiniNExT单独实现，而mininet2.3.0实现了该功能，推测是两者的实现发生了冲突。
> 
> 尝试融合，首先需要阅读代码找到异同点。

测试发现mininet 2.3.0提供的mountPrivateDirs()方法不造成冲突。

**Comment by wenkaiqiu** [comment]
多次尝试发现异常原因是mount结果与预期不符，试图从python代码中找到原因。

注：异常的mount不止影响自己的名称空间，还会影响主名称空间。

**Comment by wenkaiqiu** [comment]
发现bindObject方法中的mount与mininet中不一致，修改后测试发现仍有异常。说明bindObject不是造成异常的原因

**Comment by wenkaiqiu** [comment]
> 尝试手工方法创建名称空间，查看效果，没有发现异常。说明是名称空间创建或mount参数导致。分析尝试以下线索：
> 
> 1. 测试mxexec命令，查看是否有异常
> 2. mininet与mininext中mount使用的接口不同，尝试替换测试。

尝试路线1，发现mxexec效果与mnexec效果不同，可以确定问题根源。

**Comment by wenkaiqiu** [comment]
对比两者代码，同样调用unshare方法，为何效果不同？

![mininet](https://user-images.githubusercontent.com/14965344/51230703-f5719e00-199b-11e9-98d7-4ffa1628eddd.png)

![mininext](https://user-images.githubusercontent.com/14965344/51230616-8d22bc80-199b-11e9-8076-2f0a1698e832.png)

对比可以发现mininet中无share字段，查找[相关资料](https://segmentfault.com/a/1190000006912742)发现与mount的propagation特性有关，对照代码，找到mininet中的解决方法：
```c
/* Mark our whole hierarchy recursively as private, so that our
* mounts do not propagate to other processes.
*/
if (mount("none", "/", NULL, MS_REC|MS_PRIVATE, NULL) == -1) {
    perror("remount");
    return 1;
}
```
